[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/src/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "https://moody-music-gateway.netlify.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/storage/*"
  to = "https://moody-music-gateway.netlify.app/storage/:splat"
  status = 200
  force = true
